version: '3.1'

# we only need a db for local development
services:
  scheduler-db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: schedulerUser
      POSTGRES_PASSWORD: schedulerPassword
    ports:
      # to avoid collision with other running dbs like dou
      - 54320:5432
    volumes:
      - ./db_patches/:/docker-entrypoint-initdb.d/
