version: "3.1"

services:
  scheduler-frontend:
    build:
      context: "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}"
      args:
        - PUBLIC_URL=/scheduler
    labels:
      - "traefik.frontend.rule=PathPrefix:/scheduler"
      - "traefik.port=80"

  cypress:
    build:
      context: "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress"
    ipc: host
    command:
      [
        "./wait-for-frontend.sh",
        "scheduler-frontend:80/scheduler",
        "cypress run",
      ]
    depends_on:
      - scheduler-frontend
